# Generated by Django 4.1.1 on 2022-09-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="title",
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
