# Generated by Django 4.1.1 on 2022-09-28 21:07

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("home", "0003_project_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsedTechnology",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF", image_field=None, max_length=18, samples=None
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="experience",
            name="achievement_1",
            field=models.CharField(blank=True, default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name="experience",
            name="achievement_2",
            field=models.CharField(blank=True, default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name="experience",
            name="achievement_3",
            field=models.CharField(blank=True, default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name="experience",
            name="achievement_4",
            field=models.CharField(blank=True, default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name="experience",
            name="company",
            field=models.CharField(blank=True, default=None, max_length=256),
        ),
        migrations.AddField(
            model_name="experience",
            name="end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="job_title",
            field=models.CharField(blank=True, default="Job Title", max_length=256),
        ),
        migrations.AddField(
            model_name="experience",
            name="location",
            field=models.CharField(blank=True, default=None, max_length=256),
        ),
        migrations.AddField(
            model_name="experience",
            name="start",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="project",
            name="demo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="finished_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Finished date"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="logo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailimages.image",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="source_url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ProjectTechnologyPairs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "project",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_technologies",
                        to="home.project",
                    ),
                ),
                (
                    "used_technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.usedtechnology",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
                "unique_together": {("project", "used_technology")},
            },
        ),
    ]
