# Generated by Django 4.1.1 on 2022-09-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_usedtechnology_experience_achievement_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="icon",
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together={("name", "icon")},
        ),
    ]
