# Generated by Django 4.1.1 on 2022-09-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_skill_icon_alter_skill_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="homepage",
            name="second_name",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
