# Generated by Django 4.1.1 on 2022-09-29 22:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_experience_company_url_alter_project_finished_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="experience",
            unique_together={("job_title", "company")},
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("name", wagtail.fields.RichTextField(blank=True, null=True)),
                ("authors", wagtail.fields.RichTextField(blank=True, null=True)),
                ("journal", wagtail.fields.RichTextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("doi", models.CharField(max_length=256)),
                ("impact_factor", models.FloatField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
                "unique_together": {("name", "journal")},
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("program_name", models.CharField(max_length=128)),
                ("degree", models.CharField(max_length=128)),
                ("educational_institution", models.CharField(max_length=128)),
                ("educational_institution_url", models.URLField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(blank=True, default=None, max_length=256),
                ),
                ("start", models.DateField(default=django.utils.timezone.now)),
                ("end", models.DateField(blank=True, null=True)),
                ("gpa", models.FloatField()),
                ("max_gpa", models.FloatField(blank=True, default=5.0)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
                "unique_together": {("educational_institution", "program_name")},
            },
        ),
    ]
