# Generated by Django 4.1.1 on 2022-09-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_experience_unique_together_publication_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="faculty",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
