# Generated by Django 4.1.1 on 2022-09-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_education_faculty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="faculty",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
